# we will use openjdk 8 with alpine as it is a very small linux distro
FROM httpd:latest

 
# copying the online book store target war package from the target to 
COPY ./onlinebookstore/*  /usr/local/apache2/htdocs

EXPOSE 90